### ISSUE TITLE
How to stop price movement in price ladder

### ISSUE THREAD

**Issue by roblenderman** [OrderFlowTools/TraderLadder#24]
The default behavior of the NT SuperDom is to move the price later up and down and to keep the current price in the middle.  This makes it very hard to trade from.  I am using an alternative that keeps it steady and only moves after ten ticks away from center.  The issue is that alternative costs $400.  Is there a way for me to change the code to get the price ladder to only reset to center after an X tick move?  My coding skills are not great right now but willing to help.  I trade ES every day so I have lots of input to help the day trader.

**Comment by gemgit7** [comment]
Hi @roblenderman, I believe that is a built-in function of the NT SuperDOM. Just out of curiosity, do you have a sample video of what you're looking for?

**Comment by roblenderman** [comment]
Here are the two options.  By default, NT only gives dynamic which is
impossible to use in a market that is actually moving.  The static one can
be enabled but it suffers from a lack of columns which is what the git code
is designed to add.  One issue I have is that they will not allow static on
the account type I have asit is a licensed product based on a patent
another company owns.  Crazy but true.    Something like what you see at
the end of the second video is ideal.

https://www.youtube.com/watch?v=pw33DeFbezw

https://www.youtube.com/watch?v=_BrnmJ1nBIE



Rob

**Comment by gemgit7** [comment]
Thanks @roblenderman! It may be an option if someone decides to write a stand-alone DOM. I'm afraid this is a limitation of the DOM that NT offers.
