### ISSUE TITLE
display total changes in pulling & stacking 

### ISSUE THREAD

**Issue by ziongotoptions1** [OrderFlowTools/TraderLadder#25]
Hello i really love this software. However, one issue that i have is there is no cumulative summary of the pulling and stacking that is occurring. For example i can see the changes in the bid and ask at individual levels, but i dont see net/cumulative change in pulling and stacking. the human eye is not fast enough to see the changes in pulling and stacking, since it changes so frequently however by being able to see the total changes across the bid and ask rows, it is more useful in my opinion.

**Comment by gemgit7** [comment]
@ziongotoptions1 Thanks for the suggestion. I'll take a look to see if it is something I can add.

**Comment by ziongotoptions1** [comment]
> @ziongotoptions1 Thanks for the suggestion. I'll take a look to see if it is something I can add.

Thank you I would really appreciate it! The price ladder has been a complete game changer for me in my trading! If you were able to add that feature I could better confirm my hypothesis on order imbalances. I really appreciate you taking the time to develop this, thank you so much!
