### ISSUE TITLE
Error Install 

### ISSUE THREAD

**Issue by Trade2winnow** [OrderFlowTools/TraderLadder#7]
![Screenshot_2](https://user-images.githubusercontent.com/106371252/170651348-5b70ce2c-bb9a-4102-8af1-0d16fe1df212.jpg)
Good evening, my system has no errors I have compiled before installing, but I get this attached message, thanks for your help

**Comment by famaTV** [comment]
Hello, You may need to remove old version first before installing this.

**Comment by gemgit7** [comment]
@Trade2winnow, I believe @famaTV is correct. Please remove older versions before installing the latest version.
I've also fixed a potential issue with namespace clashes that might have caused this issue in the v0.3.6+ release as well.

**Comment by gemgit7** [comment]
@Trade2winnow do let me know if your install issue has been resolved.
